#!/usr/bin/env bash
# =============================================================================
# cloudflare-ses-dns.sh — Create SES email-sending DNS records in Cloudflare
# =============================================================================
#
# USAGE
# -----
#   # 1. Set required env vars:
#   export CF_API_TOKEN="<cloudflare-api-token>"   # Needs Zone:Edit DNS
#   export CF_ZONE_ID="<zone-id-for-slipscan.app>"
#   export EMAIL_SENDING_DOMAIN="mail.slipscan.app"   # default if unset
#   export AWS_REGION="us-east-1"                      # default if unset
#
#   # 2. Create SPF, DMARC, and MAIL FROM MX records (no DKIM tokens needed):
#   ./cloudflare-ses-dns.sh
#
#   # 3. Also create DKIM CNAMEs (tokens from SES console → Verified identities):
#   ./cloudflare-ses-dns.sh --dkim <token1> <token2> <token3>
#
# IDEMPOTENCY NOTE
# ----------------
# This script always POSTs to the Cloudflare DNS API (create, not upsert).
# If a record already exists Cloudflare will return an error indicating the
# record is a duplicate — this is safe to ignore for TXT and MX records that
# are identical, but Cloudflare does NOT deduplicate CNAMEs automatically.
# Run this script at most once per environment, or delete existing records
# in the Cloudflare dashboard first.
#
# DKIM CNAMEs
# -----------
# DKIM tokens are generated by SES and are unique per domain identity.
# Retrieve them from:
#   AWS Console → SES → Verified identities → <domain> → Authentication →
#   DKIM → View DNS records
# Or via CLI:
#   aws sesv2 get-email-identity --email-identity mail.slipscan.app \
#     --region us-east-1 --query 'DkimAttributes.Tokens'
#
# REQUIRED TOOLS
# --------------
#   curl, jq (jq is optional — errors are printed as raw JSON if absent)
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
SENDING_DOMAIN="${EMAIL_SENDING_DOMAIN:-mail.slipscan.app}"
REGION="${AWS_REGION:-us-east-1}"
MAIL_FROM_SUBDOMAIN="bounce.${SENDING_DOMAIN}"
DMARC_REPORT_EMAIL="dmarc-reports@slipscan.app"

# ---------------------------------------------------------------------------
# Validate required env vars
# ---------------------------------------------------------------------------
if [[ -z "${CF_API_TOKEN:-}" ]]; then
  echo "ERROR: CF_API_TOKEN is not set." >&2
  exit 1
fi
if [[ -z "${CF_ZONE_ID:-}" ]]; then
  echo "ERROR: CF_ZONE_ID is not set." >&2
  exit 1
fi

CF_API="https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/dns_records"

# ---------------------------------------------------------------------------
# Helper: create a DNS record via the Cloudflare API
# ---------------------------------------------------------------------------
# Usage: cf_create_record <type> <name> <content> [priority] [ttl]
cf_create_record() {
  local record_type="$1"
  local name="$2"
  local content="$3"
  local priority="${4:-}"
  local ttl="${5:-300}"

  # Build JSON payload
  local payload
  if [[ -n "$priority" ]]; then
    payload=$(printf '{"type":"%s","name":"%s","content":"%s","priority":%s,"ttl":%s,"proxied":false}' \
      "$record_type" "$name" "$content" "$priority" "$ttl")
  else
    payload=$(printf '{"type":"%s","name":"%s","content":"%s","ttl":%s,"proxied":false}' \
      "$record_type" "$name" "$content" "$ttl")
  fi

  echo "  Creating ${record_type} ${name} → ${content} ..."

  local response
  response=$(curl --silent --request POST \
    --url "$CF_API" \
    --header "Authorization: Bearer ${CF_API_TOKEN}" \
    --header "Content-Type: application/json" \
    --data "$payload")

  # Surface errors
  if command -v jq &>/dev/null; then
    local success
    success=$(echo "$response" | jq -r '.success')
    if [[ "$success" != "true" ]]; then
      local errors
      errors=$(echo "$response" | jq -r '.errors[]?.message // "unknown error"')
      echo "  WARNING: Cloudflare API returned success=false for ${record_type} ${name}: ${errors}" >&2
    else
      echo "  OK"
    fi
  else
    # jq not available — print raw response
    echo "  Response: $response"
  fi
}

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
CREATE_DKIM=false
DKIM_TOKEN1=""
DKIM_TOKEN2=""
DKIM_TOKEN3=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dkim)
      CREATE_DKIM=true
      DKIM_TOKEN1="${2:-}"
      DKIM_TOKEN2="${3:-}"
      DKIM_TOKEN3="${4:-}"
      if [[ -z "$DKIM_TOKEN1" || -z "$DKIM_TOKEN2" || -z "$DKIM_TOKEN3" ]]; then
        echo "ERROR: --dkim requires three token arguments." >&2
        echo "Usage: $0 --dkim <token1> <token2> <token3>" >&2
        exit 1
      fi
      shift 4
      ;;
    -h|--help)
      head -50 "$0" | grep '^#' | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "ERROR: Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
echo "=== Cloudflare SES DNS setup ==="
echo "Zone ID:          ${CF_ZONE_ID}"
echo "Sending domain:   ${SENDING_DOMAIN}"
echo "MAIL FROM domain: ${MAIL_FROM_SUBDOMAIN}"
echo "AWS region:       ${REGION}"
echo ""

echo "--- SPF: From-address domain (${SENDING_DOMAIN}) ---"
cf_create_record "TXT" "${SENDING_DOMAIN}" "v=spf1 include:amazonses.com ~all" "" "300"

echo ""
echo "--- DMARC (${SENDING_DOMAIN}) ---"
cf_create_record "TXT" "_dmarc.${SENDING_DOMAIN}" \
  "v=DMARC1; p=none; rua=mailto:${DMARC_REPORT_EMAIL}; fo=1" "" "3600"

echo ""
echo "--- Custom MAIL FROM: MX (${MAIL_FROM_SUBDOMAIN}) ---"
cf_create_record "MX" "${MAIL_FROM_SUBDOMAIN}" \
  "feedback-smtp.${REGION}.amazonses.com" "10" "300"

echo ""
echo "--- Custom MAIL FROM: SPF (${MAIL_FROM_SUBDOMAIN}) ---"
cf_create_record "TXT" "${MAIL_FROM_SUBDOMAIN}" \
  "v=spf1 include:amazonses.com ~all" "" "300"

if [[ "$CREATE_DKIM" == "true" ]]; then
  echo ""
  echo "--- DKIM CNAMEs ---"
  cf_create_record "CNAME" \
    "${DKIM_TOKEN1}._domainkey.${SENDING_DOMAIN}" \
    "${DKIM_TOKEN1}.dkim.amazonses.com" "" "auto"
  cf_create_record "CNAME" \
    "${DKIM_TOKEN2}._domainkey.${SENDING_DOMAIN}" \
    "${DKIM_TOKEN2}.dkim.amazonses.com" "" "auto"
  cf_create_record "CNAME" \
    "${DKIM_TOKEN3}._domainkey.${SENDING_DOMAIN}" \
    "${DKIM_TOKEN3}.dkim.amazonses.com" "" "auto"
else
  echo ""
  echo "NOTE: DKIM CNAMEs were not created (--dkim not specified)."
  echo "      Retrieve tokens from the SES console or with:"
  echo "        aws sesv2 get-email-identity --email-identity ${SENDING_DOMAIN} \\"
  echo "          --region ${REGION} --query 'DkimAttributes.Tokens'"
  echo "      Then re-run:"
  echo "        $0 --dkim <token1> <token2> <token3>"
fi

echo ""
echo "=== Done. Verify with:"
echo "  dig TXT ${SENDING_DOMAIN} +short"
echo "  dig TXT _dmarc.${SENDING_DOMAIN} +short"
echo "  dig MX  ${MAIL_FROM_SUBDOMAIN} +short"
echo "  dig TXT ${MAIL_FROM_SUBDOMAIN} +short"
if [[ "$CREATE_DKIM" == "true" ]]; then
  echo "  dig CNAME ${DKIM_TOKEN1}._domainkey.${SENDING_DOMAIN} +short"
fi
