-- File: drop-all-tables.sql
-- Description: Script to drop all tables in the database
-- CAUTION: This will delete all data in these tables. Use with care.

-- Disable row level security to allow dropping tables
ALTER TABLE IF EXISTS merchants DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payshap_targets DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS txns DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payment_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bank_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bank_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS refunds DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payouts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS webhooks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS api_keys DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS unmatched_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS reconciliation_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS transaction_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS namespaces DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS relations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS objects DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tuples DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS permissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS permission_cache DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS profiles DISABLE ROW LEVEL SECURITY;

-- Drop all tables
DROP TABLE IF EXISTS merchants CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS payshap_targets CASCADE;
DROP TABLE IF EXISTS txns CASCADE;
DROP TABLE IF EXISTS payment_groups CASCADE;
DROP TABLE IF EXISTS bank_accounts CASCADE;
DROP TABLE IF EXISTS bank_transactions CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS refunds CASCADE;
DROP TABLE IF EXISTS payouts CASCADE;
DROP TABLE IF EXISTS webhooks CASCADE;
DROP TABLE IF EXISTS api_keys CASCADE;
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS unmatched_transactions CASCADE;
DROP TABLE IF EXISTS reconciliation_log CASCADE;
DROP TABLE IF EXISTS transaction_codes CASCADE;
DROP TABLE IF EXISTS namespaces CASCADE;
DROP TABLE IF EXISTS relations CASCADE;
DROP TABLE IF EXISTS objects CASCADE;
DROP TABLE IF EXISTS tuples CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS permission_cache CASCADE;
-- DROP TABLE IF EXISTS profiles CASCADE;

-- Drop custom types if any
-- Example: DROP TYPE IF EXISTS my_custom_type CASCADE;

-- Drop functions
DROP FUNCTION IF EXISTS update_modified_column() CASCADE;
DROP FUNCTION IF EXISTS generate_handle_from_email() CASCADE;
DROP FUNCTION IF EXISTS is_service_role() CASCADE;
DROP FUNCTION IF EXISTS check_permission(UUID, TEXT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS grant_permission(UUID, TEXT, TEXT, TEXT, UUID) CASCADE;
DROP FUNCTION IF EXISTS revoke_permission(UUID, TEXT, TEXT, TEXT, UUID) CASCADE;
DROP FUNCTION IF EXISTS handle_new_user() CASCADE;

-- Drop triggers
-- DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Optionally, you can also drop extensions if they're no longer needed
-- DROP EXTENSION IF EXISTS "uuid-ossp";

-- Note: This script does not drop schemas. If you want to drop schemas as well, you'd need to add those commands.