-- File: drop-all-tables.sql
-- Description: Script to drop all tables, functions, and related objects in the database
-- CAUTION: This will delete all data in these tables. Use with care.

-- Disable row level security to allow dropping tables
ALTER TABLE IF EXISTS merchants DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payshap_targets DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS txns DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payment_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bank_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bank_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS refunds DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payouts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS webhooks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS api_keys DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS unmatched_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS reconciliation_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS transaction_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS namespaces DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS relations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS objects DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tuples DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS permissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS permission_cache DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS merchant_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS merchant_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS customer_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payment_codes DISABLE ROW LEVEL SECURITY;

-- Drop all tables
DROP TABLE IF EXISTS merchants CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS payshap_targets CASCADE;
DROP TABLE IF EXISTS txns CASCADE;
DROP TABLE IF EXISTS payment_groups CASCADE;
DROP TABLE IF EXISTS bank_accounts CASCADE;
DROP TABLE IF EXISTS bank_transactions CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS refunds CASCADE;
DROP TABLE IF EXISTS payouts CASCADE;
DROP TABLE IF EXISTS webhooks CASCADE;
DROP TABLE IF EXISTS api_keys CASCADE;
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS unmatched_transactions CASCADE;
DROP TABLE IF EXISTS reconciliation_log CASCADE;
DROP TABLE IF EXISTS transaction_codes CASCADE;
DROP TABLE IF EXISTS namespaces CASCADE;
DROP TABLE IF EXISTS relations CASCADE;
DROP TABLE IF EXISTS objects CASCADE;
DROP TABLE IF EXISTS tuples CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS permission_cache CASCADE;
DROP TABLE IF EXISTS merchant_roles CASCADE;
DROP TABLE IF EXISTS merchant_users CASCADE;
DROP TABLE IF EXISTS customer_sessions CASCADE;
DROP TABLE IF EXISTS customer_sessions CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS customer_merchants CASCADE;
DROP TABLE IF EXISTS merchant_invitations CASCADE;
DROP TABLE IF EXISTS payment_codes CASCADE;
DROP TABLE IF EXISTS payment_groups CASCADE;
DROP TABLE IF EXISTS payment_code_groups CASCADE;

-- Drop custom types if any
-- Example: DROP TYPE IF EXISTS my_custom_type CASCADE;

-- Drop functions
DROP FUNCTION IF EXISTS update_modified_column() CASCADE;
DROP FUNCTION IF EXISTS generate_handle_from_email() CASCADE;
DROP FUNCTION IF EXISTS is_service_role() CASCADE;
DROP FUNCTION IF EXISTS check_permission(UUID, TEXT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS grant_permission(UUID, TEXT, TEXT, TEXT, UUID) CASCADE;
DROP FUNCTION IF EXISTS revoke_permission(UUID, TEXT, TEXT, TEXT, UUID) CASCADE;
DROP FUNCTION IF EXISTS initialize_merchant_permissions(UUID, UUID) CASCADE;
DROP FUNCTION IF EXISTS setup_initial_merchant(UUID, TEXT, TEXT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS setup_initial_customer(UUID, TEXT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS setup_initial_payshap_target(UUID, TEXT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS setup_initial_bank_account(UUID, TEXT, TEXT, TEXT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS create_payment_group_with_simple_payment(UUID, UUID, UUID, DECIMAL, TEXT) CASCADE;
DROP FUNCTION IF EXISTS find_unique_transaction_code(UUID) CASCADE;
DROP FUNCTION IF EXISTS create_customer_session(UUID) CASCADE;

-- Drop triggers
DROP TRIGGER IF EXISTS update_merchant_modtime ON merchants;
DROP TRIGGER IF EXISTS update_customer_modtime ON customers;
DROP TRIGGER IF EXISTS update_payshap_target_modtime ON payshap_targets;
DROP TRIGGER IF EXISTS update_txn_modtime ON txns;
DROP TRIGGER IF EXISTS update_payment_group_modtime ON payment_groups;
DROP TRIGGER IF EXISTS update_bank_account_modtime ON bank_accounts;
DROP TRIGGER IF EXISTS update_bank_transaction_modtime ON bank_transactions;
DROP TRIGGER IF EXISTS update_payment_modtime ON payments;
DROP TRIGGER IF EXISTS update_refund_modtime ON refunds;
DROP TRIGGER IF EXISTS update_payout_modtime ON payouts;
DROP TRIGGER IF EXISTS update_webhook_modtime ON webhooks;
DROP TRIGGER IF EXISTS update_api_key_modtime ON api_keys;
DROP TRIGGER IF EXISTS update_unmatched_transaction_modtime ON unmatched_transactions;
DROP TRIGGER IF EXISTS update_merchant_user_modtime ON merchant_users;
DROP TRIGGER IF EXISTS update_customer_session_modtime ON customer_sessions;
